In [2]:
import spacy

In [10]:
from spacy.lang.en.stop_words import STOP_WORDS
len(STOP_WORDS)

326

In [16]:
nlp =  spacy.load("en_core_web_sm")
doc = nlp("i am learning Python and I am interested in machine learning.")
for token in doc:
    if token.is_stop:
        print(token)

i
am
and
I
am
in

In [18]:
def preprocess(text):
    doc =  nlp(text)
    no_stop_words = [token.text for token in doc if not token.is_stop]
    return (no_stop_words)

In [22]:
preprocess("Go through every token and keep it only if it is NOT a stop word.")

['token', 'stop', 'word', '.']

##### Remove stop words from pandas dataframe text column

In [25]:
import pandas as pd
df = pd.read_json("doj_press.json",lines=True)  #"Read each line as a separate JSON object and convert them into rows of a DataFrame."
df.shape

(13087, 6)

In [27]:
df.head(3)

,id,title,contents,date,topics,components
0,NaN,Convicted Bomb Plotter Sentenced to 30 Years,"PORTLAND, Oregon. – Mohamed Osman Mohamud, 23,...",2014-10-01T00:00:00-04:00,[],[National Security Division (NSD)]
1,12-919,$1 Million in Restitution Payments Announced t...,WASHINGTON – North Carolina’s Waccamaw River...,2012-07-25T00:00:00-04:00,[],[Environment and Natural Resources Division]
2,11-1002,$1 Million Settlement Reached for Natural Reso...,BOSTON– A $1-million settlement has been...,2011-08-03T00:00:00-04:00,[],[Environment and Natural Resources Division]

#### Filter out those rows that do not have any topics associated with the case

In [32]:
df = df[df.topics.str.len() != 0 ]
df.head(3)

,id,title,contents,date,topics,components
4,18-898,$100 Million Settlement Will Speed Cleanup Wor...,"The U.S. Department of Justice, the U.S. Envir...",2018-07-09T00:00:00-04:00,[Environment],[Environment and Natural Resources Division]
7,14-1412,14 Indicted in Connection with New England Com...,A 131-count criminal indictment was unsealed t...,2014-12-17T00:00:00-05:00,[Consumer Protection],[Civil Division]
19,17-1419,2017 Southeast Regional Animal Cruelty Prosecu...,The United States Attorney’s Office for the Mi...,2017-12-14T00:00:00-05:00,[Environment],"[Environment and Natural Resources Division, U..."

In [38]:
df.shape

(4688, 6)

In [42]:
df = df.head(100)
df.shape

(100, 6)

In [44]:
df["content_new"] =  df.contents.apply(preprocess)

In [54]:
len(df.contents[4])

6286